import {
  HeartPulse,
  Droplet,
  Scale,
  Activity,
  Ribbon,
  Stethoscope
} from 'lucide-react';
import { Patient } from './types';

export const translations = {
  ar: {
    appTitle: 'مسارات المرضى',
    nurseName: 'م. سارة العتيبي',
    nurseDashboard: 'لوحة الممرضة',
    online: 'متصل',
    langToggle: 'EN',
    patientsTab: 'المرضى',
    statsTab: 'الإحصائيات',
    profileTab: 'الملف الشخصي',
    welcomeTitle: 'مرحبا بك في مسارات\nنظام الرعاية المزمنة',
    welcomeDesc: 'ادارة شاملة لملفات مراجعين\nمركز صحي الجابرية',
    totalPatients: 'إجمالي المرضى',
    searchPlaceholder: 'ابحث بالاسم أو السجل المدني...',
    addPatientButton: 'إضافة مريض',
    idNumber: 'السجل المدني:',
    lastVisit: 'آخر زيارة:',
    sortBy: 'ترتيب حسب الزيارة:',
    sortAsc: 'الأقدم أولاً',
    sortDesc: 'الأحدث أولاً',
    filterAll: 'الكل (ذكر وأنثى)',
    filterMale: 'ذكر',
    filterFemale: 'أنثى',
    statsHeader: 'إحصائيات الفحوصات',
    statsDesc: 'عدد الفحوصات التي أُجريت لكل مؤشر صحي.',
    monthlyGoalSectionTitle: 'المستهدف الشهري',
    monthlyGoalMonth: 'الشهر: مايو 2025',
    monthlyGoalTitle: 'المستهدف الشهري',
    remaining: 'المتبقي',
    testsNumber: 'عدد الفحوصات',
    monthly: 'شهري',
    weekly: 'أسبوعي',
    daily: 'يومي',
    totalTests: 'إجمالي الفحوصات',
    patientCount: 'عدد المرضى',
    testsByIndicator: 'مؤشر المسارات',
    testsEvolution: 'تطور مؤشر المسارات',
    countLabel: 'العدد',
    addNewPatientTitle: 'إضافة مريض جديد',
    patientNameForm: 'اسم المريض',
    civilIdForm: 'السجل المدني',
    ageForm: 'العمر',
    phoneForm: 'رقم الجوال',
    cancel: 'إلغاء',
    savePatient: 'إضافة المريض',
    genderForm: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    chartBarTitle: 'مؤشر المسارات',
    chartLineTitle: 'تطور مؤشر المسارات',
    backToPatients: 'العودة لقائمة المرضى',
    editData: 'تعديل البيانات',
    editPatientTitle: 'تعديل بيانات المريض',
    editPatientSubtitle: 'أدخل البيانات الأساسية للمريض. الحقول المطلوبة معلمة بـ *',
    saveChanges: 'حفظ التعديلات',
    editGoalTitle: 'تعديل المستهدف الشهري',
    editGoalSubtitle: 'قم بتعديل الرقم المستهدف لهذا الشهر.',
    targetLabel: 'الرقم المستهدف',
    targetValue: 'المستهدف',
    birthDate: 'تاريخ الميلاد',
    healthIndicatorsTitle: 'المؤشرات الصحية',
    healthIndicatorsDesc: 'اضغط على أي مؤشر لعرض التحاليل والفحوصات الخاصة به',
    testCount: 'فحص',
    noTestsYet: 'لا توجد فحوصات بعد',
    lastTest: 'آخر فحص:',
    addAnalysis: 'إضافة تحليل',
    resultLabel: 'النتيجة:',
    notesLabel: 'ملاحظات:',
    latestBadge: 'الأحدث',
    backToPatientPage: 'العودة لصفحة المريض',
    addTestTitle: 'إضافة تحليل / فحص',
    indicatorLabel: 'المؤشر:',
    testNameLabel: 'اسم التحليل أو الفحص *',
    resultInputLabel: 'النتيجة *',
    procedureDateLabel: 'تاريخ الإجراء',
    statusLabel: 'الحالة',
    notesInputLabel: 'ملاحظات',
    saveTest: 'حفظ التحليل',
    cancelTest: 'إلغاء',
    smartInsights: 'تنبيهات ورؤى استباقية',
    smartInsightsDesc: 'تحليل الذكاء الاصطناعي لحالة المرضى هذا الأسبوع',
    insight1: '٢ من المرضى يحتاجون لمتابعة ضغط الدم',
    insight2: 'انخفاض في معدل الفحوصات الطبية بنسبة ١٥٪ مقارنة بالشهر الماضي',
    viewDetails: 'عرض التفاصيل',
    statusOptions: {
      normal: 'طبيعي',
      followUp: 'يحتاج متابعة',
      critical: 'حرج',
      pending: 'قيد الانتظار'
    },
    // Categories & descriptions
    bp: 'مسار الضغط',
    bpDesc: 'متابعة قراءات ضغط الدم',
    sugar: 'مسار السكر',
    sugarDesc: 'السكر التراكمي والصائم',
    obesity: 'مسار السمنة',
    obesityDesc: 'مؤشر كتلة الجسم والوزن',
    fat: 'مسار الدهون',
    fatDesc: 'الكوليسترول والدهون الثلاثية',
    breastCancer: 'مسار سرطان الثدي',
    breastCancerDesc: 'الفحوصات الدورية والماموجرام',
    colon: 'مسار القالون',
    colonDesc: 'فحوصات القولون والمنظار',
    authTitle: 'تسجيل الدخول',
    authSubtitle: 'الرجاء إدخال البريد الإلكتروني للمتابعة',
    authPhoneLabel: 'البريد الإلكتروني',
    authPhoneFieldLabel: 'رقم الجوال',
    authContinue: 'متابعة',
    authCodeTitle: 'تم إرسال كود التحقق',
    authCodeSubtitle: 'الرجاء إدخال الـ 6 أرقام التي تم إرسالها',
    authVerify: 'تحقق',
    authProfileTitle: 'لنكمل ملفكِ المهني',
    authProfileSubtitle: 'الرجاء إدخال بياناتك الأساسية',
    authNameAr: 'الاسم الكامل (بالعربية)',
    authNameEn: 'الاسم الكامل (بالإنجليزية)',
    authStaffId: 'الرقم الوظيفي',
    logout: 'تسجيل الخروج',
    authSpecialization: 'التخصص',
    authSpecOptions: {
      general: 'ممرضة عامة',
      anesthesia: 'ممرضة تخدير',
      icu: 'رعاية مركزة',
      emergency: 'طوارئ',
      other: 'أخرى'
    },
    authStart: 'البدء بالنظام',
    exportData: 'تصدير البيانات',
    excelFormat: 'ملف إكسل (Excel)',
    csvFormat: 'ملف نصي (CSV)'
  },
  en: {
    appTitle: 'Patient Pathways',
    nurseName: 'Nurse Sarah',
    nurseDashboard: 'Nurse Dashboard',
    online: 'Online',
    langToggle: 'AR',
    patientsTab: 'Patients',
    statsTab: 'Statistics',
    profileTab: 'Profile',
    welcomeTitle: 'Welcome to Chronic\nCare System Pathways',
    welcomeDesc: 'Comprehensive management of patient files\nat Al Jabriya Health Center',
    totalPatients: 'Total Patients',
    searchPlaceholder: 'Search by name or Civil ID...',
    addPatientButton: 'Add Patient',
    idNumber: 'Civil ID:',
    lastVisit: 'Last Visit:',
    sortBy: 'Sort by visit:',
    sortAsc: 'Oldest first',
    sortDesc: 'Newest first',
    filterAll: 'All (Male & Female)',
    filterMale: 'Male',
    filterFemale: 'Female',
    statsHeader: 'Examination Statistics',
    statsDesc: 'Number of tests performed for each health indicator.',
    monthly: 'Monthly',
    weekly: 'Weekly',
    daily: 'Daily',
    totalTests: 'Total Tests',
    patientCount: 'Patient Count',
    testsByIndicator: 'Tests by Indicator',
    testsEvolution: 'Tests Evolution',
    countLabel: 'Count',
    addNewPatientTitle: 'Add New Patient',
    patientNameForm: 'Patient Name',
    civilIdForm: 'Civil ID',
    ageForm: 'Age',
    phoneForm: 'Phone Number',
    cancel: 'Cancel',
    savePatient: 'Add Patient',
    genderForm: 'Gender',
    male: 'Male',
    female: 'Female',
    chartBarTitle: 'Tests by Indicator',
    chartLineTitle: 'Tests Evolution',
    backToPatients: 'Back to Patients list',
    editData: 'Edit Data',
    editPatientTitle: 'Edit Patient Data',
    editPatientSubtitle: 'Enter essential patient data. Required fields marked with *',
    saveChanges: 'Save Changes',
    editGoalTitle: 'Edit Monthly Target',
    editGoalSubtitle: 'Update the target number for this month.',
    targetLabel: 'Target Number',
    targetValue: 'Target',
    monthlyGoalSectionTitle: 'Monthly Target',
    monthlyGoalMonth: 'Month: May 2025',
    remaining: 'Remaining',
    birthDate: 'Date of Birth',
    healthIndicatorsTitle: 'Health Indicators',
    healthIndicatorsDesc: 'Click on any indicator to view its tests and examinations',
    testCount: 'test(s)',
    noTestsYet: 'No tests yet',
    lastTest: 'Last test:',
    addAnalysis: 'Add Test',
    resultLabel: 'Result:',
    notesLabel: 'Notes:',
    latestBadge: 'Latest',
    backToPatientPage: 'Back to Patient Page',
    addTestTitle: 'Add Analysis / Test',
    indicatorLabel: 'Indicator:',
    testNameLabel: 'Test or Analysis Name *',
    resultInputLabel: 'Result *',
    procedureDateLabel: 'Procedure Date',
    statusLabel: 'Status',
    notesInputLabel: 'Notes',
    saveTest: 'Save Test',
    cancelTest: 'Cancel',
    smartInsights: 'AI Smart Insights',
    smartInsightsDesc: 'AI analysis of patient status this week',
    insight1: '2 patients need blood pressure follow-up',
    insight2: '15% decrease in medical tests compared to last month',
    viewDetails: 'View Details',
    statusOptions: {
      normal: 'Normal',
      followUp: 'Needs Follow-up',
      critical: 'Critical',
      pending: 'Pending'
    },
    // Categories & descriptions
    bp: 'BP Path',
    bpDesc: 'Blood pressure readings',
    sugar: 'Sugar Path',
    sugarDesc: 'Cumulative and fasting sugar',
    obesity: 'Obesity Path',
    obesityDesc: 'BMI and weight',
    fat: 'Fat Path',
    fatDesc: 'Cholesterol and Triglycerides',
    breastCancer: 'Breast Cancer Path',
    breastCancerDesc: 'Periodic tests and Mammogram',
    colon: 'Colon Path',
    colonDesc: 'Colon and Endoscopy tests',
    extraIndicator: 'Extra Indicator',
    testsNumber: 'Number of tests',
    authTitle: 'Login',
    authSubtitle: 'Please enter your email to continue',
    authPhoneLabel: 'Email Address',
    authPhoneFieldLabel: 'Phone Number',
    authContinue: 'Continue',
    authCodeTitle: 'Verification Code Sent',
    authCodeSubtitle: 'Please enter the 6-digit code sent to',
    authVerify: 'Verify',
    authProfileTitle: "Nurse Profile",
    authProfileSubtitle: 'Professional credentials and data',
    authNameAr: 'Full Name (Arabic)',
    authNameEn: 'Full Name (English)',
    authStaffId: 'Staff ID',
    logout: 'Logout',
    authSpecialization: 'Specialization',
    authSpecOptions: {
      general: 'General Nurse',
      anesthesia: 'Anesthesia Nurse',
      icu: 'ICU Nurse',
      emergency: 'Emergency Nurse',
      other: 'Other'
    },
    authStart: 'Start System',
    exportData: 'Export Data',
    excelFormat: 'Excel File',
    csvFormat: 'CSV File'
  }
};

export const initialPatients: Patient[] = [];

export const initialGoalsData = [
  { id: 'bp', name: '', icon: HeartPulse, colorGroup: 'red', target: 0, remaining: 0 },
  { id: 'sugar', name: '', icon: Droplet, colorGroup: 'blue', target: 0, remaining: 0 },
  { id: 'obesity', name: '', icon: Scale, colorGroup: 'amber', target: 0, remaining: 0 },
  { id: 'fat', name: '', icon: Activity, colorGroup: 'purple', target: 0, remaining: 0 },
  { id: 'breastCancer', name: '', icon: Ribbon, colorGroup: 'pink', target: 0, remaining: 0 },
  { id: 'colon', name: '', icon: Stethoscope, colorGroup: 'emerald', target: 0, remaining: 0 },
];
// I will hydrate names inside the component because it requires translation

export const goalsColorsMap = {
  pink: {
    text: 'text-pink-500 dark:text-pink-400',
    tagText: 'text-pink-600 dark:text-pink-400',
    tagBorder: 'border-pink-200 dark:border-pink-500/30',
    tagBg: 'bg-pink-50/50 dark:bg-pink-500/10',
    iconBg: 'bg-pink-50 dark:bg-pink-500/10',
    filled: 'bg-pink-400 dark:bg-pink-500',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-pink-300 dark:border-pink-500/50'
  },
  red: {
    text: 'text-red-500 dark:text-red-400',
    tagText: 'text-red-600 dark:text-red-400',
    tagBorder: 'border-red-200 dark:border-red-500/30',
    tagBg: 'bg-red-50/50 dark:bg-red-500/10',
    iconBg: 'bg-red-50 dark:bg-red-500/10',
    filled: 'bg-red-500 dark:bg-red-600',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-red-300 dark:border-red-500/50'
  },
  blue: {
    text: 'text-blue-500 dark:text-blue-400',
    tagText: 'text-blue-600 dark:text-blue-400',
    tagBorder: 'border-blue-200 dark:border-blue-500/30',
    tagBg: 'bg-blue-50/50 dark:bg-blue-500/10',
    iconBg: 'bg-blue-50 dark:bg-blue-500/10',
    filled: 'bg-blue-500 dark:bg-blue-600',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-blue-300 dark:border-blue-500/50'
  },
  brown: {
    text: 'text-amber-900 dark:text-amber-500',
    tagText: 'text-amber-950 dark:text-amber-400',
    tagBorder: 'border-amber-200 dark:border-amber-900/30',
    tagBg: 'bg-amber-100/50 dark:bg-amber-900/10',
    iconBg: 'bg-amber-100 dark:bg-amber-900/10',
    filled: 'bg-amber-900 dark:bg-amber-700',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-amber-600 dark:border-amber-800/50'
  },
  amber: {
    text: 'text-amber-500 dark:text-amber-400',
    tagText: 'text-amber-600 dark:text-amber-400',
    tagBorder: 'border-amber-200 dark:border-amber-500/30',
    tagBg: 'bg-amber-50/50 dark:bg-amber-500/10',
    iconBg: 'bg-amber-50 dark:bg-amber-500/10',
    filled: 'bg-amber-400 dark:bg-amber-500',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-amber-300 dark:border-amber-500/50'
  },
  purple: {
    text: 'text-purple-500 dark:text-purple-400',
    tagText: 'text-purple-600 dark:text-purple-400',
    tagBorder: 'border-purple-200 dark:border-purple-500/30',
    tagBg: 'bg-purple-50/50 dark:bg-purple-500/10',
    iconBg: 'bg-purple-50 dark:bg-purple-500/10',
    filled: 'bg-purple-400 dark:bg-purple-500',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-purple-300 dark:border-purple-500/50'
  },
  emerald: {
    text: 'text-emerald-500 dark:text-emerald-400',
    tagText: 'text-emerald-600 dark:text-emerald-400',
    tagBorder: 'border-emerald-200 dark:border-emerald-500/30',
    tagBg: 'bg-emerald-50/50 dark:bg-emerald-500/10',
    iconBg: 'bg-emerald-50 dark:bg-emerald-500/10',
    filled: 'bg-emerald-500 dark:bg-emerald-600',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-emerald-300 dark:border-emerald-500/50'
  },
  teal: {
    text: 'text-teal-500 dark:text-teal-400',
    tagText: 'text-teal-600 dark:text-teal-400',
    tagBorder: 'border-teal-200 dark:border-teal-500/30',
    tagBg: 'bg-teal-50/50 dark:bg-teal-500/10',
    iconBg: 'bg-teal-50 dark:bg-teal-500/10',
    filled: 'bg-teal-400 dark:bg-teal-500',
    empty: 'bg-slate-100 dark:bg-slate-700/50',
    batteryBorder: 'border-teal-300 dark:border-teal-500/50'
  }
} as Record<string, any>;
